/*global define*/
define({
    CONNECTION_START : '{1} is connected to your computer，connecting to SnapPea now',
    DOWNLOADING_TIP : 'Download speed depends on your internet connection, please wait',
    SPEED_TIP : '{1}% &bull; {2}/s',
    INSTALLING_TIP : 'Do NOT restart your computer while installing, please wait',
    CREDIT_TIP : 'Please check "Install this driver software anyway" to continue installing',
    CREDIT_FALLBACK_TIP : 'There is no notification on my computer',
    RESET_USB : 'Reconnect USB cable',
    RESTART_PHONE : 'Restart your phone',
    RESTART_PC : 'Restart your computer',
    ERROR_STORAGE : 'Failed to install SnapPea on your phone, maybe because there is not enough space on your phone. SnapPea needs about 10M free space，please clean the cache or uninstall some apps and try again',
    RETRY : 'Try again',
    USB_DEBUG : 'Please check "always allow from this computer" and click "OK"',
    USB_DEBUG_OTHER : 'If your phone is using Android 4.2 or above, please turn on "USB debugging" on your phone',
    USB_FALLBACK_TIP : 'I did not see this notification, try something else',
    OFFLINE_RETRY : 'No notification, try again',
    OFFLINE_OHTER : 'I didn\'t see this notification, switch to another method',
    INSTALL_DRIVER_FAILED : 'Failed to install driver, please try reinstall again',
    DOWNLOAD_DRIVER_FAILED : 'Something is wrong with our server... please wait a few minutes and try again',
    RETRY_INSTALL_DRIVER : 'Reinstall',
    RETRY_DOWNLOAD_DRIVER : 'Download again',
    SHOW_DETAIL_RESULT : 'View full details for this error',
    USER_KILL_ADB : '{1} is preventing SnapPea connecting your phone, please close it and try again',
    USER_KILL_ADB_BTN : "Close it",
    USER_KILL_ADB_ERROR : 'Failed to close {1}，please close it manually or restart SnapPea',
    REBOOT : 'Restart computer',
    ADB_SERVER_ERROR : 'SnapPea encountered problems while connecting, please restart SnapPea',
    REBOOT_WDJ : 'Restart SnapPea',
    NO_SOLUTION : 'I\'ve tried them all but still cannot connect',
    ALLOW_INSTALL : 'Please confirm installation of SnapPea on your phone in order to connect',
    CDROM : 'You need to manually install the drivers, please click Install to continue',
    //ASK_WANDOUJIA : '始终安装不上？QQ联系豌豆公主帮您解答',
    NO_CDROM_TIP : 'I didn\'t see this notification, try something else',
    UAC_CANCELED : 'Click "OK" to allow SnapPea to install the drivers for your phone',
    NOT_TRUSTED_TIP : 'Click "Install" when you see this window to continue installing',
    CLICK : 'Click',
    REBOOT_COMPUTER : 'Restart your computer to connect'
    
});
