/*global define*/
define({
    CONNECTION_START : '检测到您的 {1} 连接电脑，豌豆荚正在为您连接',
    DOWNLOADING_TIP : '下载驱动的速度可能取决于您的网络状况，请耐心等候',
    SPEED_TIP : '{1}% &bull; {2}/s',
    INSTALLING_TIP : '驱动安装过程中不要重启电脑，请耐心等候',
    CREDIT_TIP : '请您在看到这个窗口时点击「始终安装此驱动程序」，继续安装手机驱动',
    CREDIT_FALLBACK_TIP : '电脑上没出现这个提示',
    RESET_USB : '重新插拔 USB 线',
    RESTART_PHONE : '重新启动手机',
    RESTART_PC : '重新启动豌豆荚或电脑',
    ERROR_STORAGE : '豌豆荚在您的手机上安装失败，可能是由于您的手机内存存储空间不足。安装豌豆荚需要大概 10M 的空间，请您清理手机垃圾，或者卸载一些软件后重试。',
    RETRY : '重试',
    USB_DEBUG : '请在手机弹窗勾选「一律允许使用这台计算机进行调试」，并按下「确定」',
    USB_DEBUG_OTHER : '如果您的手机是 Android 4.2 版本以上的操作系统，请在手机提示中允许「USB 调试」',
    USB_FALLBACK_TIP : '一直没看到这个提示，试试别的办法',
    OFFLINE_RETRY : '没有弹窗，再试一次',
    OFFLINE_OHTER : '没看到这个提示，试试别的办法',
    INSTALL_DRIVER_FAILED : '呃，驱动好像没安装成功，请您尝试重新安装驱动。',
    DOWNLOAD_DRIVER_FAILED : '呃，服务器好像有一些故障...请过几分钟再试吧',
    RETRY_INSTALL_DRIVER : '重新安装',
    RETRY_DOWNLOAD_DRIVER : '重新下载',
    SHOW_DETAIL_RESULT : '查看详细错误原因',
    USER_KILL_ADB : '{1} 阻止了豌豆荚连接您的手机，请关闭此程序后继续。',
    USER_KILL_ADB_BTN : "把它关掉",
    USER_KILL_ADB_ERROR : '{1} 关闭失败，需要您亲自去关掉它，或者试一下重启豌豆荚',
    REBOOT : '重启电脑',
    ADB_SERVER_ERROR : '豌豆荚链接手机过程中遇到一些障碍，请您重新启动豌豆荚后继续',
    REBOOT_WDJ : '重启豌豆荚',
    NO_SOLUTION : '都试过了，还是不能链接',
    ALLOW_INSTALL : '链接手机时，需要您在手机上允许安装豌豆荚才能正常连接',
    CDROM : '您手机的驱动安装程序需要你手动安装，请您点击安装按钮继续安装过程',
    ASK_WANDOUJIA : '始终安装不上？QQ联系豌豆公主帮您解答',
    NO_CDROM_TIP : '电脑上没出现这个提示，试试别的办法',
    UAC_CANCELED : '请点击「是」，以允许豌豆荚继续帮助您安装手机驱动',
    NOT_TRUSTED_TIP : '请您在看到这个窗口时点击「安装」，继续安装手机驱动',
    CLICK : '去点一下',
    REBOOT_COMPUTER : '电脑君说它需要重启一下才能正确连接您的手机哦。',

    USB_GUIDE_LOCAL_TITLE : '请打开「USB 调试」开关',
    USB_GUIDE_LOCAL_NEED_OPEN_DEBUG : '豌豆荚需要您打开手机上的「USB 调试」开关才能连接',
    USB_GUIDE_LOCAL_CHOOSE_VERSION : '请选择您的手机系统的版本查看相应设置方法',
    USB_GUIDE_LOCAL_GUIDE : '3.2 及以下',
    USB_GUIDE_LOCAL_GUIDE_41 : '4.0 及以上',
    USB_GUIDE_LOCAL_GUIDE_42 : '4.2',
    USB_GUIDE_LOCAL_GUIDE_MIUI : 'MIUI V5',
    USB_GUIDE_LOCAL_ALREADY_TURN_ON : '我已打开'
});
